backend:
  name: github
  branch: master
  repo: scienceadvocacyoflongisland/scienceadvocacyoflongisland.github.io # change this to your repo
  base_url: https://foam-pointy-woolen.glitch.me # change this to your OAuth server
  
publish_mode: editorial_workflow
media_folder: /assets/images/2018/food-evolution-movie

collections:
  - name: "_posts"
    label: "Posts"
    folder: "_posts"
    create: true    
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "single"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - label: "Banner and teaser images"
        name: "header"
        widget: "object"
        fields: 
          - {label: "Banner Image", name: "image", widget: "image" }
          - {label: "Teaser Image", name: "teaser", widget: "image" }

      - label: "Gallery(Optional)"
        name: "gallery"
        required: false
        label_singular: Image
        collapsed: true
        hint: "Insert this code somewhere in main body: {% include gallery %}"
        widget: "list"
        fields:
          - { label: "Main Image", name: "url", widget: "image", required: false }
          - { label: "Thumbnail Image", name: "image_path", widget: "image" }
      - {label: "Body", name: "body", widget: "markdown", default: "{% include gallery %}"}
    
  - name: "_events"
    label: "Events"
    folder: "_events"
    create: true    
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: false
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "single"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - label: "Banner and teaser images"
        name: "header"
        widget: "object"
        fields: 
          - {label: "Banner Image", name: "image", widget: "image" }
          - {label: "Teaser Image", name: "teaser", widget: "image" }
      - label: "Gallery(Optional)"
        name: "gallery"
        required: false
        label_singular: Image
        collapsed: true
        hint: "Insert this code somewhere in main body: {% include gallery %}"
        widget: "list"
        fields:
          - { label: "Main Image", name: "url", widget: "image", required: false }
          - { label: "Thumbnail Image", name: "image_path", widget: "image" }
      - {label: "Body", name: "body", widget: "markdown", default: "{% include gallery %}"}